language: node_js
node_js: 8
sudo: required
before_script: npm install -g polymer-cli @advanced-rest-client/wct-istanbub
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run polymer test --module-resolution=node --npm --plugin local
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test
    --module-resolution=node --npm --plugin sauce --job-name
    "api-summary:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}; fi
env:
  global:
    - secure: >-
        DepuU1GxM6qZoVZkCOpBbm9KFMKEZyrEZvedxEBXUdBr1bY3moVwLXPxIZyGIcWOjO43i5t2hz2yhs4Fq2+AmrzEUPnqdKuG7ifIPG4n7i/JYgFdntZuMCxAI5eU0H0It0X6a/pdx6bMglwPFbcqTJds8rs35mlVnOdXJFn5RY7PeVs2tcL3/XXiOIMnGNP2leOAIHQdzua9yCBzHuoHFCt3Ih4VKwH+UE0sZqbAZsLLhdZNXArI+PRUiHdr/Hdfw5Id/XbH6oe/CeBH4bkN7A7Y9KSNS6qjjHS05W512YQb6c5WRauLquzzkvi6Ar7DDOmCM7/EpZLNA2EmVvp2WLPD48yHaO3GWcmWizXCtyHMsHrIeAiWIjLQj9vp0xeXj1f4oDX6C9eb12LGVU1UxZFrtK+QZQvxIGHKwv70ZTJyYlCrOnwUU1GdgqXcsTSewUxZjCj0ivCqbwfIrq2iiWAWpXz3jXs2hRZgwUZGapK4IuUtbkQe0tv72w1z6igP55HSjXOj/8FiAbL67aD1zBB8c3gwd0JgAuMJwNbsX0BlRW3d3qsFxUHruNPv531cd6ji9g+ngrvS7GHGxk/JBO2vCmafYdiHDU75ghMaMU3uLh4pZl4C3BT4kdgIPtPWa6O8yJRrMaoZDEJvMm183Ae7JM27k77XsznzJYR9G9c=
    - secure: >-
        RZBf4Vck8anMIuLPGf9P9YNt8Uri4AZmjdx27C6GCzsxJ/O5vaJw+MkfzI2kKpgNZ+j8znwBrcK1Fgqwd+nmVoglWGVyFZV5Ngt0kEDB65+fV4Gz6KO6lZU1qEonWwZ14hSzyqIQBDfun71x/zM68Q18L/Jae6CjnHVPrcucyeesJHU7rgKIZntt61sv8kZ4Ta4lnC8WjnMp3/xCEEn4BIiyrY8G6ilQUhjLpMe2TzcaH0yhBt2WDxnjd4AespRhNQjbv/GM2mhzVSw1IboOYCYkA8J2ThJHZ+nZzZ8vYsgq6ZWjXkK7UL3k6ZOOItZ6GwkHzxCtBu8JmDHi4aQU20xywYbpjIdWN94KvLv/oZ9wx0+o/X5g1wFrYeky8JD7rDJFxT9Y9gArxYac80a4yChHuHcdlQLKMi0WMa8hZA7c65OeMb5SFwVRwjflBIOoN0JrrkR5SrkOOwCl4dhvreKBJwBy4TTIBUasyrERiy6uI8Xc8T8wI0riqi0spo0Mg2QAZYXe16oXHn+ECJOzq5ShL9xpRoOUMXYdOJuAZTsLZNowAWLqubB+hZhMkMprzy6QpuLSF3gbj//oRZI3OnlwZNIZkRVzMxZbfm5LRtfZnzSIstQQP4IbsuKMZFMrTtSH5Mb0tOd4yVKk5hB2oWsoB1Z3cKWALCBFCF3fMaE=
